### ISSUE TITLE
Python errors with x-tile 3.1 an multi-monitor

### ISSUE THREAD

**Issue by toma315** [giuspen/x-tile#12]
After upgrading to 3.1 I get

> $ x-tile
> WM = Xfwm4
> Traceback (most recent call last):
>   File "/usr/bin/x-tile", line 74, in <module>
>     x.reload_windows_list()
>   File "/usr/share/x-tile/modules/core.py", line 1006, in reload_windows_list
>     self.store.load_model(self)
>   File "/usr/share/x-tile/modules/core.py", line 156, in load_model
>     win_geom = support.get_geom(win_id)
> NameError: name 'win_id' is not defined

This looks like some new issue possibly limitted to multi monitor environments. Same happens in 3.0, 2.6 works for me, however.

Trying to fix this win_id error lead to some other error - at that stage I gave up trying to fix it myself.

**Comment by oz123** [comment]
I can confirm this behaviour with multi-monitor setup.

**Comment by giuspen** [comment]
Unfortunately I cannot test with a second monitor at the moment but I pushed a fix that hopefully will at least move to the next error. When possible I will test myself but if you report me the issues we can still fix in hopefully few steps

**Comment by oz123** [comment]
Thanks for your reply. 
Your latest fix helps to prevent the crash. However, windows are still only tiled in one desktop.

**Comment by giuspen** [comment]
Thanks @oz123 I'll try and get hold of a monitor to try myself

**Comment by giuspen** [comment]
should be fixed in current version

**Comment by oz123** [comment]
Thanks. That works now, although it only tiles windows on the primary screen.
