### ISSUE TITLE
[BUG] Error after run application

### ISSUE THREAD

**Issue by lesmyrmidons** [giuspen/x-tile#13]
Hello !
I install this application with ppa repository.
after run this command `x-tile w`, it return result :
```
WM = GNOME Shell
DEBUG warning _NET_WM_NAME improperly set by application
Traceback (most recent call last):
  File "/usr/bin/x-tile", line 74, in <module>
    x.reload_windows_list()
  File "/usr/share/x-tile/modules/core.py", line 1006, in reload_windows_list
    self.store.load_model(self)
  File "/usr/share/x-tile/modules/core.py", line 130, in load_model
    print("class "+title)
TypeError: can only concatenate str (not "bytes") to str
```
My config :
```
OS: Ubuntu 20.04 focal
Kernel: x86_64 Linux 5.4.0-31-generic
Shell: zsh 5.8
Resolution: 3840x1080
DE: GNOME 3.36.2
Disk: 408G / 953G (45%)
CPU: Intel Core i9-7920X @ 24x 4.3GHz [60.0°C]
GPU: GeForce GTX 1060 6GB
RAM: 6810MiB / 63992MiB
```

**Comment by giuspen** [comment]
Thanks @lesmyrmidons can you try the latest from github master

**Comment by lesmyrmidons** [comment]
Hello @giuspen !
 
Yes,

My problem resolved after restart my computer.

I'm not used to shutting down my PC so I realized it quite late.
